apiVersion: batch/v1
kind: CronJob
metadata:
  name: namucrol
  labels:
    type: crol
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: namucrol
            image: rkrkrr/namucrol:latest
            imagePullPolicy: Never
            envFrom:
            - configMapRef:
               name: dbconfig
               
            
          restartPolicy: OnFailure